package it.pennino.uni.piazzaAffari.comuni.model;
// Generated 11-set-2017 21.30.31 by Hibernate Tools 5.2.1.Final

/**
 * Province generated by hbm2java
 */
public class Province implements java.io.Serializable {

	private Integer idProvincia;
	private int idRegione;
	private String nomeProvincia;
	private String siglaProvincia;

	public Province() {
	}

	public Province(int idRegione, String nomeProvincia, String siglaProvincia) {
		this.idRegione = idRegione;
		this.nomeProvincia = nomeProvincia;
		this.siglaProvincia = siglaProvincia;
	}

	public Integer getIdProvincia() {
		return this.idProvincia;
	}

	public void setIdProvincia(Integer idProvincia) {
		this.idProvincia = idProvincia;
	}

	public int getIdRegione() {
		return this.idRegione;
	}

	public void setIdRegione(int idRegione) {
		this.idRegione = idRegione;
	}

	public String getNomeProvincia() {
		return this.nomeProvincia;
	}

	public void setNomeProvincia(String nomeProvincia) {
		this.nomeProvincia = nomeProvincia;
	}

	public String getSiglaProvincia() {
		return this.siglaProvincia;
	}

	public void setSiglaProvincia(String siglaProvincia) {
		this.siglaProvincia = siglaProvincia;
	}

}
