package it.pennino.uni.piazzaAffari.comuni.model;
// Generated 11-set-2017 21.30.31 by Hibernate Tools 5.2.1.Final

/**
 * Regioni generated by hbm2java
 */
public class Regioni implements java.io.Serializable {

	private Integer idRegione;
	private String abb;
	private String nomeRegione;

	public Regioni() {
	}

	public Regioni(String abb, String nomeRegione) {
		this.abb = abb;
		this.nomeRegione = nomeRegione;
	}

	public Integer getIdRegione() {
		return this.idRegione;
	}

	public void setIdRegione(Integer idRegione) {
		this.idRegione = idRegione;
	}

	public String getAbb() {
		return this.abb;
	}

	public void setAbb(String abb) {
		this.abb = abb;
	}

	public String getNomeRegione() {
		return this.nomeRegione;
	}

	public void setNomeRegione(String nomeRegione) {
		this.nomeRegione = nomeRegione;
	}

}
